### BONJOUR CATHERINE, ICI JEAN-HUGUES ROY
### TOUS MES COMMENTAIRES SERONT EN MAJUSCULES ET PRÉCÉDÉS DE 3 # (HASHTAGS)

### TU COMMENCES TRÈS BIEN

### COMME JE VOUS DEMANDE DE METTRE 10151 URL DANS UNE LISTE, ON PEUT COMMENCER PAR CRÉER UNE LISTE QUI, POUR LE MOMENT, EST VIDE
urls = []

# for a in range(19999,30151): ### EN COMMENÇANT À 19999, TU AURAIS 10152 URLS.
for a in range(20000,30151): ### TU PEUX COMMENCER À 20000.
    
    # mc_url= "https://montrealcampus.ca?p={page_number}" .format(page_number = a) ### CETTE LIGNE FONCTIONNE, MAIS IL EST PRÉFÉRABLE DE NE PAS METTRE D'ESPACE AVANT LE POINT QUI PRÉCÈDE LES FONCTIONS
    mc_url= "https://montrealcampus.ca?p={}".format(a) ### IL N'EST PAS NÉCESSAIRE, NON PLUS, DE CRÉER UNE NOUVELLE VARIABLE ET DE METTRE SON NOM ENTRE LES ACCOLADES
    
    print(mc_url)

    # mc_url.append(a) ### APPEND FONCTIONNE AVEC DES VARIABLES DE TYPE LISTE. ICI, TU L'APPLIQUES À UNE VARIABLE DE TYPE TEXTE (STRING)
    urls.append(mc_url) ### ICI, ON AJOUTE, À CHAQUE ITÉRATION DE LA BOUCLE, LA VARIABLE "mc_url"; 

    print(len(mc_url)) ### ICI, TU AFFICHES LA LONGUEUR DE L'URL, QUI EST TOUJOURS LA MÊME (33 CARACTÈRES)

### APRÈS LA BOUCLE, TU PEUX AFFICHER SON CONTENU ET SA TAILLE.
print(urls,len(urls))

### ENFIN, IL MANQUAIT DES COMMENTAIRES DANS TON CODE POUR QUE TU M'EXPLIQUES CE QUE TU SOUHAITAIS FAIRE.